#!/bin/bash

echo Install plex

sudo docker create \
    --name=plex \
    --net=host \
    -e VERSION=latest \
    -e PUID=1000 -e PGID=1000 \
    -e TZ=Europe/Amsterdam \
    -v ~/plex/config:/config \
    -v ~/plex/data/tv:/data/tvshows \
    -v ~/plex/data/movies:/data/movies \
    -v ~/plex/transcode:/transcode \
    --restart unless-stopped \
linuxserver/plex

echo Plex installed. Starting plex

sudo docker start plex

echo Installing Sonarr

sudo docker create \
    --name sonarr \
    -p 8989:8989 \
    -e PUID=1000 -e PGID=1000 \
    -v /dev/rtc:/dev/rtc:ro \
    -v ~/plex/sonarrconfig:/config \
    -v ~/plex/data/tv:/tv \
    -v ~/plex/download:/downloads \
    --restart unless-stopped \
    linuxserver/sonarr

echo Sonarr installed. Starting sonarr

sudo docker start sonarr



echo installing Jackett

sudo docker create --name=jackett \
-v ~/plex/jackettconfig:/config \
-v ~/plex/downloads:/downloads \
-e PGID=1000 -e PUID=1000 \
-e TZ=Europe/Amsterdam \
-p 9117:9117 \
--restart unless-stopped \
linuxserver/jackett

sudo docker start jackett


echo Installing deluge

sudo docker create \
    --name deluge \
    --net=host \
    -e PUID=1000 -e PGID=1000 \
    -e TZ=Europe/Amsterdam \
    -v ~/plex/download:/downloads \
    -v ~/plex/delugeconfig:/config \
    --restart unless-stopped \
    linuxserver/deluge

echo Deluge installed. Starting Deluge

sudo docker start deluge

echo Installing htpcmanager
sudo docker create --name=htpcmanager \
     -v ~/plex/htpcmanagerconfig:/config \
     -e PGID=1000 -e PUID=1000 \
     -e TZ=Europe/Amsterdam \
     -p 8085:8085 \
     --restart unless-stopped \
     linuxserver/htpcmanager

echo htpcmanager installed. Starting it

sudo docker start htpcmanager

echo Installing plexpy
sudo docker create \
  --name=plexpy \
  -v ~/plex/plexpyconfig:/config \
  -v ~/plex/plexpylogs:/logs:ro \
  -e PGID=1000 -e PUID=1000  \
  -e TZ=Europe/Amsterdam \
  -p 8181:8181 \
  --restart unless-stopped \
  linuxserver/plexpy
echo plexpy installed. Starting it
sudo docker start plexpy

echo installing ombi
sudo docker create \
    --name=ombi \
    -v /etc/localtime:/etc/localtime:ro \
    -v ~plex/ombiconfig:/config \
    -e PGID=1000 -e PUID=1000  \
    -e TZ=Europe/Amsterdam \
    -p 3579:3579 \
    --restart unless-stopped \
    linuxserver/ombi

sudo docker start ombi
echo installed and started ombi

echo configure plex with port: 32400
echo configure sonarr with port: 8989
echo configure deluge with port: 8112
echo configure htpcmanager with port: 8085
echo configure nextcloud via localhost

echo gg wp
